# Generated by Django 5.2.9 on 2025-12-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The text of the todo item', max_length=200)),
                ('completed', models.BooleanField(default=False, help_text='Whether the todo is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the todo was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the todo was last updated')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
